<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitb4d3e6033432a687b2b5e8321fbb10f4
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Gravity_Forms\Gravity_Forms\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Gravity_Forms\Gravity_Forms\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitb4d3e6033432a687b2b5e8321fbb10f4', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Gravity_Forms\Gravity_Forms\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitb4d3e6033432a687b2b5e8321fbb10f4', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Gravity_Forms\Gravity_Forms\Composer\Autoload\ComposerStaticInitb4d3e6033432a687b2b5e8321fbb10f4::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
