<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit49751edc136d2c5c128db9706324f10f
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Gravity_Forms\Gravity_Forms\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Gravity_Forms\Gravity_Forms\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit49751edc136d2c5c128db9706324f10f', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Gravity_Forms\Gravity_Forms\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit49751edc136d2c5c128db9706324f10f', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Gravity_Forms\Gravity_Forms\Composer\Autoload\ComposerStaticInit49751edc136d2c5c128db9706324f10f::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
