<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Gravity_Forms\\Gravity_Forms\\WP\\McpSchema\\' => array($vendorDir . '/wordpress/php-mcp-schema/src'),
    'Gravity_Forms\\Gravity_Forms\\WP\\MCP\\' => array($vendorDir . '/wordpress/mcp-adapter/includes'),
    'Gravity_Forms\\Gravity_Forms\\Automattic\\Jetpack\\Autoloader\\' => array($vendorDir . '/automattic/jetpack-autoloader/src'),
);
